### ISSUE TITLE
'bower install' downloads outdated files

### ISSUE THREAD

**Issue by muenchdo** [qb-project/jsonforms#79]
When installing JSONForms via `bower install jsonforms` I end up with outdated files (the date in the copyright header is 2015-06-29).
Is this on purpose since the latest changes have not been officially *'released'* yet or is this some kind of Bower registry caching issue?

**Comment by sdirix** [comment]
You are right the latest changes are not released yet. Bower uses the git tags of the repository to distribute the files. Our latest tag is from 2015-06-09 so everything works as intended ;)

We will release a new version later today!

**Comment by muenchdo** [comment]
Great! Thanks for the quick reply and sorry for the confusion ;)
